### ISSUE TITLE
Support for IAM users?

### ISSUE THREAD

**Issue by brunomcustodio** [hashicorp/vault-plugin-auth-gcp#10]
Is support for IAM users in your plans for the near-future? It would be very useful if regular users could authenticate with Vault using their (personal or Organization) GCP credentials in order to manage secrets.

**Comment by emilymye** [comment]
I assume you are talking about Google IAM credentials (i.e. a OAuth2 access token)? I'm interested as well but I think if we did do it, we'd probably create a seperate plugin, either as a Google Identity backend or a generic OAuth2 backend of some sort.

**Comment by brunomcustodio** [comment]
@emilymye yes, that's what I was talking about :) is this in your plans / are you open to contribution?

**Comment by emilymye** [comment]
I wouldn't say it's our current priority, at least within this repo, for a couple of reasons:

1. If you are interacting with GCP, you should probably be operating using a service account instead of your user credentials, as recommended by GCP [authentication docs](https://cloud.google.com/docs/authentication/end-user)

2. I think this would be a new plugin/backend in the main Vault repo. The user objects would have  very different authorization flows than the GCP entities (i.e. user/group bindings to Vault policies, similar to the Github auth backend, with no actual calls to GCP APIs to verify identity). 

In fact, I think  [#2525 on the main Vault repo](https://github.com/hashicorp/vault/issues/2525) is a generic OIDC backend that would essentially be what you are describing. If you want to bump/contribute, that issue is probably the best place to start.

If you do feel like this is a more urgent use case, we can probably discuss priorities or I can jump onto that thread. I'm pretty sure that the Hashicorp team has explicitly mentioned not wanting to have one-off OIDC backends for each identity platform so I don't see us prioritizing a backend just for Google.

**Comment by brunomcustodio** [comment]
@emilymye thank you, and sorry for the delay. Thanks for the detailed explanation — makes perfect sense. 💯

Perhaps this issue can be closed?
