### ISSUE TITLE
role_id is not returned when creating/updating a role

### ISSUE THREAD

**Issue by mark-rushakoff** [hashicorp/vault-plugin-auth-gcp#154]
I am programmatically creating a GCP role, which is intended to be used as an identity entity alias.

I expected that creating the role would return the role ID, but it doesn't:

```console
$ vault write -format=json auth/gcp/role/deleteme type=gce token_ttl=24h
{
  "request_id": "2613bc5c-126f-3eb2-b8da-84861cc65780",
  "lease_id": "",
  "lease_duration": 0,
  "renewable": false,
  "data": null,
  "warnings": null
}
```

I can work around this by reading back the role:

```console
$ vault read -format=json auth/gcp/role/deleteme
{
  "request_id": "563f933a-437e-2b97-84b3-5ae541592f37",
  "lease_id": "",
  "lease_duration": 0,
  "renewable": false,
  "data": {
    "add_group_aliases": false,
    "role_id": "7e12bfca-e209-bfa3-8e98-c9c2674ff1fd",
    "token_bound_cidrs": [],
    "token_explicit_max_ttl": 0,
    "token_max_ttl": 0,
    "token_no_default_policy": false,
    "token_num_uses": 0,
    "token_period": 0,
    "token_policies": [],
    "token_ttl": 86400,
    "token_type": "default",
    "type": "gce"
  },
  "warnings": null
}
```

But it seems like the role ID should be returned during creation, so I don't have to make an additional request to the Vault server.

I am on Vault v1.12.x.

**Comment by maxcoulombe** [comment]
Hey @mark-rushakoff, thanks for submitting this issue. Historically, Vault made the choice to not return a payload on the majority of create or update requests for a couple of reasons:

* Because vault resources are identified by a provided human-readable name instead of a generated ID, like deleteme in your example, returning the object is not necessary for subsequent queries
* Some Vault APIs receive a pretty significant amount of traffic, so even if it seems extremely small in most cases, not returning a payload that gets ignored most of the time saves resources
* Because Vault deals with sensitive information, it generally errs on the side of terseness and does not give any information it is not explicitly requested to limit how/when this information could be mishandled just due to some oversight

I understand and agree that most APIs should return created or updated objects as a convenience so the client does not need to do an additional request. But in Vault's case unless there is an important use case beyond convenience we do not plan to change the current behaviour.
