### ISSUE TITLE
GCP Auth IAM (using Vault Cluster on K8s) - Error (could not find service account key or Google Oauth cert with given 'kid' id) 

### ISSUE THREAD

**Issue by samuelbaruffi** [hashicorp/vault-plugin-auth-gcp#51]
Hello,

We are running Vault on GKE (used the https://github.com/kelseyhightower/vault-on-google-kubernetes-engine tutorial).

We would like to use the GCP Auth IAM backend, and we've followed the https://www.vaultproject.io/docs/auth/gcp.html tutorial but we're having issues trying to authenticate with a vault with the signed JWT token.

We have done the following procedures:

```
### Enable GCP Auth Backend on Vault ###
vault auth-enable gcp
```

```
### Write the credentials empty because we're using K8s on GKE (is this correct?) ###
vault write auth/gcp/config credentials=
```

```
### Create a new Service Account with permission to sign tokens ### 
Created vault-admin service account on the same project on GCP with the permissions to sign token
```

```
### Created the role on Vault ###
GOOGLE_PROJECT=project-12345
SERVICE_ACCOUNT=vault-admin@${GOOGLE_PROJECT}.iam.gserviceaccount.com
vault write auth/gcp/role/dev-role \
    type="iam" \
    project_id="${GOOGLE_PROJECT}" \
    policies="default" \
    service_accounts="${SERVICE_ACCOUNT}"
```

```
### Create the Json login request ###
GOOGLE_PROJECT=project-12345
SERVICE_ACCOUNT=vault-admin@${GOOGLE_PROJECT}.iam.gserviceaccount.com
cat - > login_request.json <<EOF
{
    "aud": "vault/dev-role",
    "sub": "${SERVICE_ACCOUNT}",
    "exp": $((EXP=$(date +%s)+600))
}
EOF
```

```
### Requested a signed JWT token ###
JWT_TOKEN=$(gcloud beta iam service-accounts sign-jwt login_request.json \
    signed_jwt.json \
    --iam-account=${SERVICE_ACCOUNT} && cat signed_jwt.json)
```

```
### Try to login using the signed JWT token from above ###
vault write -field=token auth/gcp/login role=dev-role jwt=${JWT_TOKEN} > ~/.vault-token
```

```
### This is where the following error occurs: ###
Error writing data to auth/gcp/login: Error making API request.

URL: PUT https://10.161.0.5:8200/v1/auth/gcp/login
Code: 400. Errors:

* could not find service account key or Google Oauth cert with given 'kid' id
```

We would highly appreciate some help on this issue since we are stuck.

We also have some questions:

1) Do I need to specify the credentials.json on `vault write auth/gcp/config credentials=` if we are using the Vault Cluster on K8s (via the tutorial: https://github.com/kelseyhightower/vault-on-google-kubernetes-engine), if yes, where can i find the credentials.json?

2) I created the new service account called `vault-admin`, can I use this service account to generate and sign the token?

Thanks in advance and let me know if you require more information/logs about the issue.

Sam.

**Comment by emilymye** [comment]
> `* could not find service account key or Google Oauth cert with given 'kid' id`

Generally we see this error when we got an error from GET serviceAccount/my-service-account/key/kid. Usually this is because [the IAM API has not been enabled](https://cloud.google.com/apis/docs/enable-disable-apis) in the GCP project. Otherwise, it might be that your Vault admin service account doesn't have permissions to get the key.

> I created the new service account called vault-admin, can I use this service account to generate and sign the token?

Technically, you can. I'm going to be explicit, just in case, since we are talking about many service accounts. There are three service accounts to consider:

1. `$USER`: The Vault user who wants to login and get a Vault auth token
2. `$VAULT_ADMIN`: Service account that has permissions to verify `$USER` (i.e. call IAM API methods keys.get() and serviceAccounts.get() to verify) 
3. `$SIGNER`: Service account that has permissions to call [signJWT](https://cloud.google.com/iam/reference/rest/v1/projects.serviceAccounts/signJwt) on `$USER`.

It sounds like you are asking if `$SIGNER` can be `$VAULT_ADMIN`? The answer is yes - technically, these three accounts can be all the same, all different, etc. For the most part, we actually assume `$USER` and `$SIGNER` are the same. You actually only need the JSON credentials for `$SIGNER`, to call `signJWT`, and for `$VAULT_ADMIN`, so Vault can call GCP APIs.

The reason why you might not want to use the `$VAULT_ADMIN` to sign is to limit the scope of these credentials. `$VAULT_ADMIN` credentials belong to the Vault server first and foremost, and you can imagine that this account tends to have a fairly scary set of permissions. On the other hand, the $SIGNER/$USER belong to the Vault client/user who is asking for privileges. 


> ### Create the Json login request ###
> ...

We actually created a client-side helper that does this JWT construction for you, which is much easier.  See the second command in [this section](https://www.vaultproject.io/docs/auth/gcp.html#authentication). To re-copy here, it looks like:

```
vault login -method=gcp \
    role="my-role" \
    jwt_exp="15m" \
    credentials=@path/to/credentials.json \ <-- $SIGNER, can be omitted for Application Default creds
    project="my-project" \
    service_account="service-account@my-project.iam.gserviceaccounts.com" <-- $USER
```

> Do I need to specify the credentials.json on vault write auth/gcp/config credentials= if we are using the Vault Cluster on K8s (via the tutorial: https://github.com/kelseyhightower/vault-on-google-kubernetes-engine), if yes, where can i find the credentials.json?

Application Default Credentials should work if you have set the admin account on your GKE instances,  without needing to write to `vault write auth/gcp/config`.

**Comment by samuelbaruffi** [comment]
Hello @emilymye !

Thank you so much for the clarification and help.

I was getting confused on the way the three different service accounts were handled.

I solved my problem by disabling and reenabling the auth/GCP on vault (so that way the old config was gone).

Also, I had to give some new IAM roles for the VAULT_ADMIN service account, as follow:

![screen shot 2018-10-03 at 11 37 44 am](https://user-images.githubusercontent.com/7096709/46431480-c98a1f80-c700-11e8-9672-b58faeb99f6a.png)

I would recommend if Vault/Google could add on their documentation what you've described below, it would help a lot of people not getting confused. At least, I wasn't able to find that info in the docs (maybe I did not look properly).

Thanks for your help! Highly appreciated the fast and clarifying response!

**Comment by tuannvm** [comment]
Hi @samuelbaruffi and @emilymye, I just re-evaluate this issue, and here are the updated permissions needed:

- VAULT_ADMIN
```
Service Account Key Admin
```

- VAULT_SIGNER
```
Service Account Token Creator
```

That's all!

**Comment by ralimardanov** [comment]
Hello @samuelbaruffi, @emilymye and @tuannvm!
Have you used this for cross project authentication?
I have Vault in one project in GKE and application, which need to get secrets in another project. We are using Spring Cloud Vault for that.
I have service account for this application inside GKE(we use workload identity for this), which has Token Creator role only.
But when I try to login/get credentials from Vault I see such errors:
inside application:
```
Cannot login using GCP-IAM: could not find service account 'projects/-/serviceAccounts/<sa_name>': googleapi: Error 403: Permission iam.serviceAccounts.get is required to perform this operation on service account projects/-/serviceAccounts/<sa_name>., forbidden; nested exception is org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 Internal Server Error:
```

via gcloud console:
```
_URL: PUT http://<vault_addr>/v1/auth/gcp/login
Code: 500. Errors:

* could not find service account 'projects/-/serviceAccounts/<sa_name>': googleapi: Error 403: Permission iam.serviceAccounts.get is required to perform this operation on service account projects/-/serviceAccounts/<sa_name>, forbidden_
```
